In [1]:
import pandas as pd

In [2]:
dump = pd.read_excel('/home/gus/MEGAsync/zim/main/Yale/Projects/G_fuscipes/Gff_database/dump_database_for_mary_b/consolidated_old_and_2014_Gff_db_dump_FROM_OPENREFINE.xls')

In [3]:
dump.head()

,pre_openrefine_file,comment,date,dead,fly_number,hunger_stage,kept_in,sex,species,teneral,...,mrsA_PCR sample volume,mrsA_Seq,population,public_notes,size,source_file,species_identification_method_id,specimen_id,box_id,tube_num
0,2014_excel_db.xls#Sheet1,!blank,2014-07-22 00:00:00,False,1,2,EtOH,F,Gff,False,...,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank
1,2014_excel_db.xls#Sheet1,!blank,2014-07-22 00:00:00,False,2,3,EtOH,F,Gff,False,...,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank
2,2014_excel_db.xls#Sheet1,!blank,2014-07-22 00:00:00,False,3,3,EtOH,M,Gff,False,...,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank
3,2014_excel_db.xls#Sheet1,!blank,2014-07-22 00:00:00,False,4,3,EtOH,M,Gff,False,...,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank
4,2014_excel_db.xls#Sheet1,!blank,2014-07-22 00:00:00,False,5,3,EtOH,M,Gff,False,...,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank,!blank