In [ ]:
from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt

map = Basemap(llcrnrlon=30.182,llcrnrlat=-1.317,urcrnrlon=37.283,urcrnrlat=2.849, resolution = 'h', epsg=4326)

map.drawmapboundary(fill_color='aqua')
#Fill the continents with the land color
map.fillcontinents(color='coral',lake_color='aqua')
map.drawcountries(linewidth=0.25)
map.drawcoastlines()
 
plt.show()

In [1]:
import pandas as pd

from fuzzywuzzy import fuzz
from fuzzywuzzy import process

import random as rand

In [2]:
run /home/gus/Documents/YalePostDoc/project_stuff/g_f_fucipes_uganda/scripts/gff_pandas_database.py

Main dataframe is dfp: and is only Gff.

/home/gus/Documents/YalePostDoc/project_stuff/g_f_fucipes_uganda/scripts/gff_pandas_database.py:330: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  if 'NAN' in exc.message.upper():

In [3]:
run /home/gus/Documents/YalePostDoc/project_stuff/g_f_fucipes_uganda/scripts/2015-03-24_looking_for_infections_in_old_files.py

/home/gus/anaconda2/envs/stack2/lib/python2.7/site-packages/pandas/core/indexing.py:490: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item_labels[indexer[info_axis]]] = value
/home/gus/anaconda2/envs/stack2/lib/python2.7/site-packages/pandas/core/indexing.py:415: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

'provided_dataframes' contains refs to useful dataframes.

In [4]:
# Load Chaz MSAT individuals
table_msat = pd.read_csv('/home/gus/Documents/YalePostDoc/project_stuff/g_f_fucipes_uganda/microsat/GffMsats_1480individuals_ID_list.csv')
table_msat.head(10)

  Fly Number
0   AM11e001
1   AM11e002
2   AM11e003
3   AM11e004
4   AM11e005
5   AM11e006
6   AM11e008
7   AM11e009
8   AM11e010
9   AM11e013

In [5]:
provided_dataframes.keys()

['df_samples',
 'traps_gps_uganda',
 'villages_gps_uganda',
 'wolbachia_data_orig',
 'uganda',
 'df_tryps',
 'table_latlon']

# From looking at papers southern sites include:

- BK
- BKD
- BN
- BU
- BV
- BY
- BZ
- DB
- EB
- IGG
- JN
- KF
- KG
- KIS
- KL
- KO
- LI
- MA
- MGG
- MK
- NA
- NAM
- ND
- NS
- OK
- OS
- PT
- SA
- TB

In [6]:
df_samples.iloc[rand.sample(range(len(df_samples)), 10)]

,aliguot_n,aliquot_n,banked_sample_id,collection_date,collection_id,collection_id.1,curation_date,curator,food_state,id,internal_notes,internal_notes.1,life_stage,population,public_notes,sex,size,species_id,species_id.1,species_identification,species_identification_method_id,specimen_id,stoage,storage,submission_date,submitter,tissue,tube_num
473,NaN,NaN,OK09091,2009-04-01 00:00:00,OKXX,NaN,,,,,,NaN,,OK,Storage=N/A,F,1,G. fuscipes,NaN,NaN,,NaN,NaN,NaN,2010-06-15 00:00:00,J Beadell;B Symula;U Alam,NaN,
18,NaN,,NA1.19,2008-12-03 00:00:00,NAXX-2008,NaN,,,,,,NaN,,NA,,M,1,G. fuscipes,NaN,NaN,,,NaN,,2010-06-01,J Beadell;B Symula;U Alam,,19
79,NaN,NaN,JN1.87,4/x/08,JN01-2008,NaN,,,,,,NaN,,JN,N/A,M,1,G. fuscipes,NaN,NaN,,NaN,NaN,NaN,2010-06-05 00:00:00,J Beadell;B Symula;U Alam,NaN,87
24,NaN,NaN,BU10.5,2008-03-13 00:00:00,BU10-2008,NaN,,,,,,NaN,,BU,storage=S002,F,1,G. fuscipes,NaN,NaN,,NaN,NaN,NaN,2010-06-01,J Beadell;B Symula;U Alam,NaN,5
51,NaN,,Apac-L114,2007-08-14 00:00:00,APXX-2007,NaN,,,,,,NaN,,,,M,1,G. fuscipes,NaN,NaN,,,NaN,,,,,L114
60,NaN,NaN,BV08022,4/x/08,Bvbulk,NaN,,,,,,NaN,,BV,storage N/A,M,1,G. fuscipes,NaN,NaN,,NaN,NaN,NaN,2010-06-06 00:00:00,J Beadell;B Symula;U Alam,NaN,22
52,NaN,NaN,BU10.33,39520,BU10-2008,NaN,,,,,,NaN,,BU,storage=S002,M,1,G. fuscipes,NaN,NaN,,NaN,NaN,NaN,2010-06-01,J Beadell;B Symula;U Alam,NaN,33
234,NaN,NaN,SI5.2,2008-03-13 00:00:00,SI05-2008,NaN,,,,,,NaN,,SI,storage=S002,F,1,G. fuscipes,NaN,NaN,,NaN,NaN,NaN,2010-06-01,J Beadell;B Symula;U Alam,NaN,2
215,NaN,NaN,KL09085,4/x/09,KLXX-2009,NaN,,,,,,NaN,,KL,storage N/A,M,1,G. fuscipes,NaN,NaN,,NaN,NaN,NaN,2010-06-17 00:00:00,J Beadell;B Symula;U Alam,NaN,85
9,NaN,NaN,OY09023,2009-07-17 00:00:00,OY01-2009,NaN,,,,,,NaN,,OY,Storage=N/A,N/A,1,G. fuscipes,NaN,NaN,,NaN,NaN,NaN,2010-06-17 00:00:00,J Beadell;B Symula;U Alam,NaN,

In [7]:
def fuzzy_filter(item, targets):
    """Returns boolean if filter is successfull on ``item``.

    Args:
        item (str): string in dataframe column to be filtered
        targets (list): list of location codes we want from the database.

    Returns:
        boolean
    """

    hit = process.extractOne(item, targets)
    return hit[-1] >= 80

def mask_by_fuzzy(targets, db_col):
    """Creates extraction mask to pull out targets from db based on fuzzy matching.
    
    Args:
        targets (list): list of location codes we want from the database.
        db_col (Series): dataframe column representing the vaules to be filtered.
    

    Returns:
        pandas mask
    """
    
    mask = db_col.apply(fuzzy_filter, targets=targets)
    
    return mask

In [8]:
south_locs = ["BK","BKD","BN","BU","BV","BY","BZ","DB","EB","IGG","JN","KF","KG","KIS","KL","KO","LI","MA","MGG","MK","NA","NAM","ND","NS","OK","OS","PT","SA","TB"]

In [9]:
hit = process.extractOne(u'NAM',table_msat['Fly Number'])
print hit
hit[-1] >= 80

('NAM11_156', 90)

True

In [33]:
hit2 = process.extractOne('bv', table_msat['Fly Number'])
print hit2[-1] >= 80
print hit2

False
('BK09e0100', 45)

In [10]:
south_mask = mask_by_fuzzy(targets=south_locs, db_col=df_samples.banked_sample_id)
south_mask.head()

0    False
1    False
2    False
3    False
4    False
Name: banked_sample_id, dtype: bool

In [11]:
smask = uganda.id.apply(lambda x: True if x in south_locs else False)

In [12]:
south_villages = uganda.query("latitude <= 1.481837")
south_villages

,id,name,gaz_id,latitude,longitude,country,district,village_code
2,BB,Bulanga B,,1.068104,33.777342,Uganda,Budaka,BB
3,BB20,Bulanga B Trap 20,,1.072800,33.779530,Uganda,Budaka,BB
4,BB21,Bulanga B Trap 21,,1.072500,33.779380,Uganda,Budaka,BB
5,BB22,Bulanga B Trap 22,,1.072130,33.778800,Uganda,Budaka,BB
6,BB23,Bulanga B Trap 23,,1.071740,33.778950,Uganda,Budaka,BB
7,BB24,Bulanga B Trap 24,,1.071960,33.779000,Uganda,Budaka,BB
8,BB25,Bulanga B Trap 25,,1.065930,33.778490,Uganda,Budaka,BB
9,BB26,Bulanga B Trap 26,,1.065930,33.776830,Uganda,Budaka,BB
10,BB27,Bulanga B Trap 27,,1.062750,33.774090,Uganda,Budaka,BB
11,BB28,Bulanga B Trap 28,,1.062980,33.774180,Uganda,Budaka,BB
12,BB29,Bulanga B Trap 29,,1.062320,33.774170,Uganda,Budaka,BB
13,BD,Budonga,,0.260933,33.929463,Uganda,Busia,BD
14,BD14,Budonga Trap 14,,0.260770,33.929420,Uganda,Busia,BD
15,BD15,Budonga Trap 15,,0.260860,33.929550,Uganda,Busia,BD
16,BD16,Budonga Trap 16,,0.261170,33.929420,Uganda,Busia,BD
31,BK,Nabiswa,,1.006550,33.857650,Uganda,Pallisa,BK
32,BK,Nabiswa,,1.012690,33.861300,Uganda,Pallisa,BK
33,BK,Kadama,,1.010407,33.861218,Uganda,Pallisa,BK
34,BK01,Nabiswa location 1,,1.006550,33.857650,Uganda,Pallisa,BK
35,BK01,Nabiswa Trap 1,,1.012690,33.861300,Uganda,Pallisa,BK
36,BK01,Kadama Trap 1,,1.012480,33.861290,Uganda,Pallisa,BK
37,BK02,Nabiswa location 2,,1.006810,33.857370,Uganda,Pallisa,BK
38,BK02,Nabiswa Trap 2,,1.012260,33.861540,Uganda,Pallisa,BK
39,BK02,Kadama Trap 2,,1.012720,33.861500,Uganda,Pallisa,BK
40,BK03,Nabiswa Trap 3,,1.012310,33.861520,Uganda,Pallisa,BK
41,BK03,Kadama Trap 3,,1.012290,33.861470,Uganda,Pallisa,BK
42,BK04,Nabiswa Trap 4,,1.012480,33.861260,Uganda,Pallisa,BK
43,BK04,Kadama Trap 4,,1.012270,33.861260,Uganda,Pallisa,BK
44,BK05,Kadama Trap 5,,1.006660,33.860790,Uganda,Pallisa,BK
45,BK06,Nabiswa Trap 6,,1.006840,33.857380,Uganda,Pallisa,BK
46,BK07,Nabiswa Trap 7,,1.006530,33.857170,Uganda,Pallisa,BK
47,BK08,Nabiswa Trap 8,,1.006530,33.857410,Uganda,Pallisa,BK
48,BK08,Kadama Trap 8,,1.006020,33.861000,Uganda,Pallisa,BK
49,BN,Bunghazi,,0.940966,33.973218,Uganda,Butaleja,BN
50,BN01,Bunghazi Trap 1,,0.935130,33.976430,Uganda,Butaleja,BN
51,BN02,Bunghazi Trap 2,,0.935280,33.976580,Uganda,Butaleja,BN
52,BN03,Bunghazi Trap 3,,0.935840,33.976890,Uganda,Butaleja,BN
53,BN04,Bunghazi Trap 4,,0.934420,33.977150,Uganda,Butaleja,BN
54,BN05,Bunghazi Trap 5,,0.935560,33.976630,Uganda,Butaleja,BN
55,BN06,Bunghazi Trap 6,,0.935690,33.976830,Uganda,Butaleja,BN
56,BN07,Bunghazi Trap 7,,0.935940,33.976930,Uganda,Butaleja,BN
57,BN08,Bunghazi Trap 8,,0.936220,33.976800,Uganda,Butaleja,BN
58,BN09,Bunghazi Trap 9,,0.942040,33.968650,Uganda,Butaleja,BN
59,BN10,Bunghazi Trap 10,,0.951690,33.968990,Uganda,Butaleja,BN
60,BN11,Bunghazi Trap 11,,0.951720,33.968810,Uganda,Butaleja,BN
61,BN12,Bunghazi Trap 12,,0.951890,33.971000,Uganda,Butaleja,BN
62,BN13,Bunghazi Trap 13,,0.945160,33.969410,Uganda,Butaleja,BN
63,BN14,Bunghazi Trap 14,,0.946280,33.968160,Uganda,Butaleja,BN
64,BN15,Bunghazi Trap 15,,0.941630,33.969010,Uganda,Butaleja,BN
66,BU,Busime,,0.248867,33.970927,Uganda,Busia,BU
...,...,...,...,...,...,...,...,...
143,KY,Kyere,,1.449669,33.657465,Uganda,Soroti,KY
144,KY01,Kyere Trap 1,,1.442360,33.668460,Uganda,Soroti,KY
145,KY02,Kyere Trap 2,,1.442190,33.666940,Uganda,Soroti,KY
146,KY03,Kyere Trap 3,,1.452740,33.654430,Uganda,Soroti,KY
147,KY04,Kyere Trap 4,,1.452900,33.653610,Uganda,Soroti,KY
148,KY05,Kyere Trap 5,,1.452370,33.653750,Uganda,Soroti,KY
149,KY06,Kyere Trap 6,,1.450990,33.653510,Uganda,Soroti,KY
150,KY07,Kyere Trap 7,,1.452200,33.654650,Uganda,Soroti,KY
151,KY08,Kyere Trap 8,,1.451600,33.654370,Uganda,Soroti,KY
165,MK,Mukongoro,,1.358237,33.873001,Uganda,Kumi,MK
166,MK01,Mukongoro Trap 1,,1.349170,33.896820,Uganda,Kumi,MK
167,MK02,Mukongoro Trap 2,,1.347500,33.895920,Uganda,Kumi,MK
168,MK03,Mukongoro Trap 3,,1.412500,33.920790,Uganda,Kumi,MK
169,MK04,Mukongoro Trap 4,,1.413060,33.920130,Uganda,Kumi,MK
170,MK05,Mukongoro Trap 5,,1.356690,33.794290,Uganda,Kumi,MK
171,MK06,Mukongoro Trap 6,,1.356810,33.793400,Uganda,Kumi,MK
172,MK07,Mukongoro Trap 7,,1.357050,33.792390,Uganda,Kumi,MK
173,MK08,Mukongoro Trap 8,,1.357500,33.791690,Uganda,Kumi,MK
174,MK09,Mukongoro Trap 9,,1.347090,33.894530,Uganda,Kumi,MK
175,MK10,Mukongoro Trap 10,,1.347120,33.894100,Uganda,Kumi,MK
176,MK11,Mukongoro Trap 11,,1.347060,33.893960,Uganda,Kumi,MK
177,MK12,Mukongoro Trap 12,,1.348220,33.894180,Uganda,Kumi,MK
178,MK13,Mukongoro Trap 13,,1.348900,33.898590,Uganda,Kumi,MK
179,MK14,Mukongoro Trap 14,,1.348710,33.898060,Uganda,Kumi,MK
180,MK15,Mukongoro Trap 15,,1.347440,33.895920,Uganda,Kumi,MK
181,MK16,Mukongoro Trap 16,,1.346980,33.893250,Uganda,Kumi,MK
182,MP,Mpanga Village,,0.303520,30.532090,Uganda,Kamwenge,MP
228,NA,Namadumu,,0.904193,33.873963,Uganda,Butaleja,NA
229,NA,Nkumba,,0.058590,32.531980,Uganda,Wakiso,NA
230,NA01,Namadumu Trap 1,,0.903840,33.874490,Uganda,Butaleja,NA
231,NA02,Namadumu Trap 2,,0.904290,33.874170,Uganda,Butaleja,NA
232,NA03,Namadumu Trap 3,,0.904450,33.873230,Uganda,Butaleja,NA
233,NA04,Namadumu Trap 4,,0.903810,33.873290,Uganda,Butaleja,NA
234,NB,Namutumba,,0.863130,33.729290,Uganda,Namutumba,NB
239,OK,Okame River,,0.519209,34.118511,Uganda,Busia,OK
240,OK01,Okame River Trap 1,,0.520290,34.117100,Uganda,Busia,OK
241,OK02,Okame River Trap 2,,0.520850,34.115560,Uganda,Busia,OK
242,OK03,Okame River Trap 3,,0.522120,34.115000,Uganda,Busia,OK
243,OK04,Okame River Trap 4,,0.523070,34.114170,Uganda,Busia,OK
244,OK05,Okame River Trap 5,,0.517010,34.122650,Uganda,Busia,OK
245,OK06,Okame River Trap 6,,0.517310,34.122410,Uganda,Busia,OK
246,OK07,Okame River Trap 7,,0.517970,34.121050,Uganda,Busia,OK
247,OK08,Okame River Trap 8,,0.518080,34.120430,Uganda,Busia,OK
248,OK09,Okame River Trap 9,,0.519400,34.119100,Uganda,Busia,OK
249,OK10,Okame River Trap 10,,0.519850,34.117640,Uganda,Busia,OK
261,SI,Sitengo,,0.260303,34.017557,Uganda,Busia,SI
262,SI05,Sitengo Trap 5,,0.260740,34.017550,Uganda,Busia,SI
263,SI06,Sitengo Trap 6,,0.260190,34.017590,Uganda,Busia,SI
264,SI07,Sitengo Trap 7,,0.259980,34.017530,Uganda,Busia,SI
269,TR,Tororo,,0.612080,34.185535,Uganda,Abwanget,TR

In [22]:
south_villages.query("village_code == 'BV'")

,id,name,gaz_id,latitude,longitude,country,district,village_code
73,BV,Buvuma Island,,0.47416,33.38236,Uganda,Mukono,BV
74,BV01,Buvuma Island Trap 1,,1.34698,33.89325,Uganda,Mukono,BV
75,BV11,Buvuma Island Trap 11,,0.25643,33.20635,Uganda,Mukono,BV
76,BV12,Buvuma Island Trap 12,,0.30733,33.29325,Uganda,Mukono,BV
77,BV13,Buvuma Island Trap 13,,0.31060,33.29360,Uganda,Mukono,BV
78,BV14,Buvuma Island Trap 14,,0.31209,33.30392,Uganda,Mukono,BV
79,BV15,Buvuma Island Trap 15,,0.31153,33.30379,Uganda,Mukono,BV

In [20]:
south_villages_gps = south_villages[['latitude','longitude','village_code']].groupby('village_code').mean()
south_villages_gps

              latitude  longitude
village_code
BB            1.068104  33.777342
BD            0.260933  33.929463
BK            1.009727  33.860004
BN            0.940966  33.973218
BU            0.248867  33.970927
BV            0.474160  33.382360
JN            1.332193  32.738184
KA            1.046104  33.771181
KB            0.977190  30.546500
KK            0.364650  30.279960
KL            0.166700  32.766700
KP            1.007965  33.855469
KT            0.082080  32.485050
KW            1.017428  33.874041
KY            1.449669  33.657465
MK            1.358237  33.873001
MP            0.303520  30.532090
NA            0.763196  33.650187
NB            0.863130  33.729290
OK            0.519560  34.118511
SI            0.260303  34.017557
TR            0.612080  34.185535

In [17]:
south_villages_gps.to_clipboard()

In [33]:
mask_ = mask_by_fuzzy(targets=south_villages.village_code.unique(), db_col=table_msat["Fly Number"])
mask_.head()

0    False
1    False
2    False
3    False
4    False
Name: Fly Number, dtype: bool

In [35]:
genotyped_from_south = table_msat[mask_]
genotyped_from_south

          Fly Number
30         BK09e0100
31         BK09e0104
32         BK09e0107
33         BK09e0111
34         BK09e0113
35         BK09e0114
36         BK09e0116
37         BK09e0119
38         BK09e0121
39         BK09e0131
40         BK09e0133
41         BK09e0135
42         BK09e0136
43         BK09e0141
44         BK09e0152
45         BK09e0156
46         BK09e0161
47         BK09e0162
48         BK09e0173
49         BK09e0175
50         BK09e0176
51         BK09e0179
52         BK09e0181
53         BK09e0186
54         BK09e0188
55         BK09e0190
56         BK09e0192
57         BK09e0195
58         BK09e0196
59         BK09e0199
60         BK09e0202
61         BK09e0203
62         BK09e0204
63         BK09e0210
64         BK09e0218
65         BK09e0221
66         BK09e0225
67         BK09e0228
68         BK09e0229
69         BK09e0232
70           BK09001
71           BK09003
72           BK09004
73           BK09005
74           BK09008
75           BK09010
76           BK09011
77           BK09012
78           BK09013
79           BK09014
...              ...
1011        OKb09059
1012        OKb09061
1013        OKb09062
1014        OKb09063
1015        OKb09064
1016        OKb09065
1017        OKb09066
1018        OKb09067
1019          OK1001
1020          OK1002
1021          OK1003
1022          OK1005
1023           OK207
1024          OK4027
1025          OK4028
1026          OK4029
1027          OK4030
1028          OK4031
1029          OK4032
1030          OK4033
1031          OK4034
1032          OK4037
1033          OK4038
1034          OK4039
1035          OK4040
1036          OK4041
1037          OK4042
1038          OK4043
1039          OK4044
1040          OK4045
1041          OK4053
1042          OK4054
1043          OK4055
1044          OK4056
1045          OK4057
1046          OK4058
1047           OK701
1048           OK702
1049           OK707
1050           OK801
1051           OK803
1052           OK804
1053           OK805
1054           OK806
1055           OK901
1056           OK902
1057           OK903
1408         KB4_G35
1409         KL5_G79
1479  Gff_ETH-Kl1022

[699 rows x 1 columns]

In [37]:
len(genotyped_from_south)

699

In [38]:
genotyped_from_south.to_clipboard()

# Get Robert a list of likely southern genotyped flies

In [ ]:
# df_samples_typed = pd.merge(left=table_msat, right=df_samples, 
#                              how='inner', 
#                              on=None, left_on="Fly Number", right_on="banked_sample_id", 
#                              left_index=False, right_index=False, 
#                              sort=False, suffixes=('_x', '_y'), copy=True)


# # df_samples_typed  # these ONLY contain BK09 tubes

In [ ]:
# df_samples_typed = pd.merge(left=table_msat, right=df_samples, 
#                              how='inner', 
#                              on=None, left_on="Fly Number", right_on="banked_sample_id", 
#                              left_index=False, right_index=False, 
#                              sort=False, suffixes=('_x', '_y'), copy=True)